package org.clesun.entity;

public class DEquipmentParameter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_equipment_parameter.parament_id
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    private Long paramentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_equipment_parameter.equipment_addr
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    private String equipmentAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_equipment_parameter.equipment_unitname
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    private String equipmentUnitname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_equipment_parameter.equipment_address
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    private String equipmentAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_equipment_parameter.equipment_orgname
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    private String equipmentOrgname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_equipment_parameter.equipment_unittype
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    private String equipmentUnittype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_equipment_parameter.equipment_lng
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    private Double equipmentLng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_equipment_parameter.equipment_lat
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    private Double equipmentLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_equipment_parameter.remark
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_equipment_parameter.post_code
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_equipment_parameter.city_name
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    private String cityName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_equipment_parameter.parament_id
     *
     * @return the value of d_equipment_parameter.parament_id
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public Long getParamentId() {
        return paramentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_equipment_parameter.parament_id
     *
     * @param paramentId the value for d_equipment_parameter.parament_id
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public void setParamentId(Long paramentId) {
        this.paramentId = paramentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_equipment_parameter.equipment_addr
     *
     * @return the value of d_equipment_parameter.equipment_addr
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public String getEquipmentAddr() {
        return equipmentAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_equipment_parameter.equipment_addr
     *
     * @param equipmentAddr the value for d_equipment_parameter.equipment_addr
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public void setEquipmentAddr(String equipmentAddr) {
        this.equipmentAddr = equipmentAddr == null ? null : equipmentAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_equipment_parameter.equipment_unitname
     *
     * @return the value of d_equipment_parameter.equipment_unitname
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public String getEquipmentUnitname() {
        return equipmentUnitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_equipment_parameter.equipment_unitname
     *
     * @param equipmentUnitname the value for d_equipment_parameter.equipment_unitname
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public void setEquipmentUnitname(String equipmentUnitname) {
        this.equipmentUnitname = equipmentUnitname == null ? null : equipmentUnitname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_equipment_parameter.equipment_address
     *
     * @return the value of d_equipment_parameter.equipment_address
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public String getEquipmentAddress() {
        return equipmentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_equipment_parameter.equipment_address
     *
     * @param equipmentAddress the value for d_equipment_parameter.equipment_address
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public void setEquipmentAddress(String equipmentAddress) {
        this.equipmentAddress = equipmentAddress == null ? null : equipmentAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_equipment_parameter.equipment_orgname
     *
     * @return the value of d_equipment_parameter.equipment_orgname
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public String getEquipmentOrgname() {
        return equipmentOrgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_equipment_parameter.equipment_orgname
     *
     * @param equipmentOrgname the value for d_equipment_parameter.equipment_orgname
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public void setEquipmentOrgname(String equipmentOrgname) {
        this.equipmentOrgname = equipmentOrgname == null ? null : equipmentOrgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_equipment_parameter.equipment_unittype
     *
     * @return the value of d_equipment_parameter.equipment_unittype
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public String getEquipmentUnittype() {
        return equipmentUnittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_equipment_parameter.equipment_unittype
     *
     * @param equipmentUnittype the value for d_equipment_parameter.equipment_unittype
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public void setEquipmentUnittype(String equipmentUnittype) {
        this.equipmentUnittype = equipmentUnittype == null ? null : equipmentUnittype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_equipment_parameter.equipment_lng
     *
     * @return the value of d_equipment_parameter.equipment_lng
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public Double getEquipmentLng() {
        return equipmentLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_equipment_parameter.equipment_lng
     *
     * @param equipmentLng the value for d_equipment_parameter.equipment_lng
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public void setEquipmentLng(Double equipmentLng) {
        this.equipmentLng = equipmentLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_equipment_parameter.equipment_lat
     *
     * @return the value of d_equipment_parameter.equipment_lat
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public Double getEquipmentLat() {
        return equipmentLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_equipment_parameter.equipment_lat
     *
     * @param equipmentLat the value for d_equipment_parameter.equipment_lat
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public void setEquipmentLat(Double equipmentLat) {
        this.equipmentLat = equipmentLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_equipment_parameter.remark
     *
     * @return the value of d_equipment_parameter.remark
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_equipment_parameter.remark
     *
     * @param remark the value for d_equipment_parameter.remark
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_equipment_parameter.post_code
     *
     * @return the value of d_equipment_parameter.post_code
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_equipment_parameter.post_code
     *
     * @param postCode the value for d_equipment_parameter.post_code
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_equipment_parameter.city_name
     *
     * @return the value of d_equipment_parameter.city_name
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_equipment_parameter.city_name
     *
     * @param cityName the value for d_equipment_parameter.city_name
     *
     * @mbggenerated Thu Jun 28 11:03:25 CST 2018
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }
}