package org.clesun.entity;

import java.util.Date;

public class DFarm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.farm_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Long farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.farm_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String farmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.farm_nickname
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String farmNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.manage_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String manageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.farm_logo_path
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String farmLogoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.location_lng
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Double locationLng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.location_lat
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Double locationLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.farm_province
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String farmProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.farm_city
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String farmCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.farm_county
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String farmCounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.farm_town
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String farmTown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.farm_subdistrict
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String farmSubdistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.farm_address
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String farmAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.scope_json
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String scopeJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.farm_introduction
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String farmIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.email
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.phone_no
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.postal_code
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String postalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.business_license_code
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String businessLicenseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.registered_capital
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Double registeredCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.registered_time
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Date registeredTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.create_time
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.plan_investment
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Double planInvestment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.legal_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String legalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.business_code
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Long businessCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.business_scop
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String businessScop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.farm_type_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Long farmTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.farm_type
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String farmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.total_area
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Double totalArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.plant_area
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Double plantArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.farm_remark
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String farmRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.telephone_no
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String telephoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.total_investment
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Double totalInvestment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.fixed_assets
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Double fixedAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.office_area
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Double officeArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.production_area
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Double productionArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.regional_nature
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String regionalNature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.product_parent_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Long productParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.product_parent_value
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String productParentValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.product_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.plant_breed_area
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Double plantBreedArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.total_yield
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Double totalYield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.product_price
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Double productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.price_unit
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String priceUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.is_leading_enterprise
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String isLeadingEnterprise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.is_brush
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String isBrush;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.is_stop
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String isStop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.enterprise_level
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String enterpriseLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.breed_product_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String breedProductName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.breeding_stock
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Integer breedingStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.male_num
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Integer maleNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.female_num
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Integer femaleNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.out_column
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String outColumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.is_env_assessment
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String isEnvAssessment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.facilities_resources
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String facilitiesResources;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.project_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.Improvement_capital
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Double improvementCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_farm.farm_summary
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String farmSummary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.farm_id
     *
     * @return the value of d_farm.farm_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Long getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.farm_id
     *
     * @param farmId the value for d_farm.farm_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFarmId(Long farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.farm_name
     *
     * @return the value of d_farm.farm_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getFarmName() {
        return farmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.farm_name
     *
     * @param farmName the value for d_farm.farm_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFarmName(String farmName) {
        this.farmName = farmName == null ? null : farmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.farm_nickname
     *
     * @return the value of d_farm.farm_nickname
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getFarmNickname() {
        return farmNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.farm_nickname
     *
     * @param farmNickname the value for d_farm.farm_nickname
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFarmNickname(String farmNickname) {
        this.farmNickname = farmNickname == null ? null : farmNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.manage_name
     *
     * @return the value of d_farm.manage_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getManageName() {
        return manageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.manage_name
     *
     * @param manageName the value for d_farm.manage_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setManageName(String manageName) {
        this.manageName = manageName == null ? null : manageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.farm_logo_path
     *
     * @return the value of d_farm.farm_logo_path
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getFarmLogoPath() {
        return farmLogoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.farm_logo_path
     *
     * @param farmLogoPath the value for d_farm.farm_logo_path
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFarmLogoPath(String farmLogoPath) {
        this.farmLogoPath = farmLogoPath == null ? null : farmLogoPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.location_lng
     *
     * @return the value of d_farm.location_lng
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Double getLocationLng() {
        return locationLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.location_lng
     *
     * @param locationLng the value for d_farm.location_lng
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setLocationLng(Double locationLng) {
        this.locationLng = locationLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.location_lat
     *
     * @return the value of d_farm.location_lat
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Double getLocationLat() {
        return locationLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.location_lat
     *
     * @param locationLat the value for d_farm.location_lat
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setLocationLat(Double locationLat) {
        this.locationLat = locationLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.farm_province
     *
     * @return the value of d_farm.farm_province
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getFarmProvince() {
        return farmProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.farm_province
     *
     * @param farmProvince the value for d_farm.farm_province
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFarmProvince(String farmProvince) {
        this.farmProvince = farmProvince == null ? null : farmProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.farm_city
     *
     * @return the value of d_farm.farm_city
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getFarmCity() {
        return farmCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.farm_city
     *
     * @param farmCity the value for d_farm.farm_city
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFarmCity(String farmCity) {
        this.farmCity = farmCity == null ? null : farmCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.farm_county
     *
     * @return the value of d_farm.farm_county
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getFarmCounty() {
        return farmCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.farm_county
     *
     * @param farmCounty the value for d_farm.farm_county
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFarmCounty(String farmCounty) {
        this.farmCounty = farmCounty == null ? null : farmCounty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.farm_town
     *
     * @return the value of d_farm.farm_town
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getFarmTown() {
        return farmTown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.farm_town
     *
     * @param farmTown the value for d_farm.farm_town
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFarmTown(String farmTown) {
        this.farmTown = farmTown == null ? null : farmTown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.farm_subdistrict
     *
     * @return the value of d_farm.farm_subdistrict
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getFarmSubdistrict() {
        return farmSubdistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.farm_subdistrict
     *
     * @param farmSubdistrict the value for d_farm.farm_subdistrict
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFarmSubdistrict(String farmSubdistrict) {
        this.farmSubdistrict = farmSubdistrict == null ? null : farmSubdistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.farm_address
     *
     * @return the value of d_farm.farm_address
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getFarmAddress() {
        return farmAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.farm_address
     *
     * @param farmAddress the value for d_farm.farm_address
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFarmAddress(String farmAddress) {
        this.farmAddress = farmAddress == null ? null : farmAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.scope_json
     *
     * @return the value of d_farm.scope_json
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getScopeJson() {
        return scopeJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.scope_json
     *
     * @param scopeJson the value for d_farm.scope_json
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setScopeJson(String scopeJson) {
        this.scopeJson = scopeJson == null ? null : scopeJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.farm_introduction
     *
     * @return the value of d_farm.farm_introduction
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getFarmIntroduction() {
        return farmIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.farm_introduction
     *
     * @param farmIntroduction the value for d_farm.farm_introduction
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFarmIntroduction(String farmIntroduction) {
        this.farmIntroduction = farmIntroduction == null ? null : farmIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.email
     *
     * @return the value of d_farm.email
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.email
     *
     * @param email the value for d_farm.email
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.phone_no
     *
     * @return the value of d_farm.phone_no
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.phone_no
     *
     * @param phoneNo the value for d_farm.phone_no
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.postal_code
     *
     * @return the value of d_farm.postal_code
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.postal_code
     *
     * @param postalCode the value for d_farm.postal_code
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode == null ? null : postalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.business_license_code
     *
     * @return the value of d_farm.business_license_code
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getBusinessLicenseCode() {
        return businessLicenseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.business_license_code
     *
     * @param businessLicenseCode the value for d_farm.business_license_code
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setBusinessLicenseCode(String businessLicenseCode) {
        this.businessLicenseCode = businessLicenseCode == null ? null : businessLicenseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.registered_capital
     *
     * @return the value of d_farm.registered_capital
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Double getRegisteredCapital() {
        return registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.registered_capital
     *
     * @param registeredCapital the value for d_farm.registered_capital
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setRegisteredCapital(Double registeredCapital) {
        this.registeredCapital = registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.registered_time
     *
     * @return the value of d_farm.registered_time
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Date getRegisteredTime() {
        return registeredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.registered_time
     *
     * @param registeredTime the value for d_farm.registered_time
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setRegisteredTime(Date registeredTime) {
        this.registeredTime = registeredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.create_time
     *
     * @return the value of d_farm.create_time
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.create_time
     *
     * @param createTime the value for d_farm.create_time
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.plan_investment
     *
     * @return the value of d_farm.plan_investment
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Double getPlanInvestment() {
        return planInvestment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.plan_investment
     *
     * @param planInvestment the value for d_farm.plan_investment
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setPlanInvestment(Double planInvestment) {
        this.planInvestment = planInvestment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.legal_name
     *
     * @return the value of d_farm.legal_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getLegalName() {
        return legalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.legal_name
     *
     * @param legalName the value for d_farm.legal_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setLegalName(String legalName) {
        this.legalName = legalName == null ? null : legalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.business_code
     *
     * @return the value of d_farm.business_code
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Long getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.business_code
     *
     * @param businessCode the value for d_farm.business_code
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setBusinessCode(Long businessCode) {
        this.businessCode = businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.business_scop
     *
     * @return the value of d_farm.business_scop
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getBusinessScop() {
        return businessScop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.business_scop
     *
     * @param businessScop the value for d_farm.business_scop
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setBusinessScop(String businessScop) {
        this.businessScop = businessScop == null ? null : businessScop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.farm_type_id
     *
     * @return the value of d_farm.farm_type_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Long getFarmTypeId() {
        return farmTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.farm_type_id
     *
     * @param farmTypeId the value for d_farm.farm_type_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFarmTypeId(Long farmTypeId) {
        this.farmTypeId = farmTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.farm_type
     *
     * @return the value of d_farm.farm_type
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getFarmType() {
        return farmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.farm_type
     *
     * @param farmType the value for d_farm.farm_type
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFarmType(String farmType) {
        this.farmType = farmType == null ? null : farmType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.total_area
     *
     * @return the value of d_farm.total_area
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Double getTotalArea() {
        return totalArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.total_area
     *
     * @param totalArea the value for d_farm.total_area
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setTotalArea(Double totalArea) {
        this.totalArea = totalArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.plant_area
     *
     * @return the value of d_farm.plant_area
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Double getPlantArea() {
        return plantArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.plant_area
     *
     * @param plantArea the value for d_farm.plant_area
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setPlantArea(Double plantArea) {
        this.plantArea = plantArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.farm_remark
     *
     * @return the value of d_farm.farm_remark
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getFarmRemark() {
        return farmRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.farm_remark
     *
     * @param farmRemark the value for d_farm.farm_remark
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFarmRemark(String farmRemark) {
        this.farmRemark = farmRemark == null ? null : farmRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.telephone_no
     *
     * @return the value of d_farm.telephone_no
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getTelephoneNo() {
        return telephoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.telephone_no
     *
     * @param telephoneNo the value for d_farm.telephone_no
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setTelephoneNo(String telephoneNo) {
        this.telephoneNo = telephoneNo == null ? null : telephoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.total_investment
     *
     * @return the value of d_farm.total_investment
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Double getTotalInvestment() {
        return totalInvestment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.total_investment
     *
     * @param totalInvestment the value for d_farm.total_investment
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setTotalInvestment(Double totalInvestment) {
        this.totalInvestment = totalInvestment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.fixed_assets
     *
     * @return the value of d_farm.fixed_assets
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Double getFixedAssets() {
        return fixedAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.fixed_assets
     *
     * @param fixedAssets the value for d_farm.fixed_assets
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFixedAssets(Double fixedAssets) {
        this.fixedAssets = fixedAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.office_area
     *
     * @return the value of d_farm.office_area
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Double getOfficeArea() {
        return officeArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.office_area
     *
     * @param officeArea the value for d_farm.office_area
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setOfficeArea(Double officeArea) {
        this.officeArea = officeArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.production_area
     *
     * @return the value of d_farm.production_area
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Double getProductionArea() {
        return productionArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.production_area
     *
     * @param productionArea the value for d_farm.production_area
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setProductionArea(Double productionArea) {
        this.productionArea = productionArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.regional_nature
     *
     * @return the value of d_farm.regional_nature
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getRegionalNature() {
        return regionalNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.regional_nature
     *
     * @param regionalNature the value for d_farm.regional_nature
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setRegionalNature(String regionalNature) {
        this.regionalNature = regionalNature == null ? null : regionalNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.product_parent_id
     *
     * @return the value of d_farm.product_parent_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Long getProductParentId() {
        return productParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.product_parent_id
     *
     * @param productParentId the value for d_farm.product_parent_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setProductParentId(Long productParentId) {
        this.productParentId = productParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.product_parent_value
     *
     * @return the value of d_farm.product_parent_value
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getProductParentValue() {
        return productParentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.product_parent_value
     *
     * @param productParentValue the value for d_farm.product_parent_value
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setProductParentValue(String productParentValue) {
        this.productParentValue = productParentValue == null ? null : productParentValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.product_name
     *
     * @return the value of d_farm.product_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.product_name
     *
     * @param productName the value for d_farm.product_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.plant_breed_area
     *
     * @return the value of d_farm.plant_breed_area
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Double getPlantBreedArea() {
        return plantBreedArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.plant_breed_area
     *
     * @param plantBreedArea the value for d_farm.plant_breed_area
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setPlantBreedArea(Double plantBreedArea) {
        this.plantBreedArea = plantBreedArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.total_yield
     *
     * @return the value of d_farm.total_yield
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Double getTotalYield() {
        return totalYield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.total_yield
     *
     * @param totalYield the value for d_farm.total_yield
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setTotalYield(Double totalYield) {
        this.totalYield = totalYield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.product_price
     *
     * @return the value of d_farm.product_price
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Double getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.product_price
     *
     * @param productPrice the value for d_farm.product_price
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setProductPrice(Double productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.price_unit
     *
     * @return the value of d_farm.price_unit
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getPriceUnit() {
        return priceUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.price_unit
     *
     * @param priceUnit the value for d_farm.price_unit
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setPriceUnit(String priceUnit) {
        this.priceUnit = priceUnit == null ? null : priceUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.is_leading_enterprise
     *
     * @return the value of d_farm.is_leading_enterprise
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getIsLeadingEnterprise() {
        return isLeadingEnterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.is_leading_enterprise
     *
     * @param isLeadingEnterprise the value for d_farm.is_leading_enterprise
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setIsLeadingEnterprise(String isLeadingEnterprise) {
        this.isLeadingEnterprise = isLeadingEnterprise == null ? null : isLeadingEnterprise.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.is_brush
     *
     * @return the value of d_farm.is_brush
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getIsBrush() {
        return isBrush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.is_brush
     *
     * @param isBrush the value for d_farm.is_brush
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setIsBrush(String isBrush) {
        this.isBrush = isBrush == null ? null : isBrush.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.is_stop
     *
     * @return the value of d_farm.is_stop
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getIsStop() {
        return isStop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.is_stop
     *
     * @param isStop the value for d_farm.is_stop
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setIsStop(String isStop) {
        this.isStop = isStop == null ? null : isStop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.enterprise_level
     *
     * @return the value of d_farm.enterprise_level
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getEnterpriseLevel() {
        return enterpriseLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.enterprise_level
     *
     * @param enterpriseLevel the value for d_farm.enterprise_level
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setEnterpriseLevel(String enterpriseLevel) {
        this.enterpriseLevel = enterpriseLevel == null ? null : enterpriseLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.breed_product_name
     *
     * @return the value of d_farm.breed_product_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getBreedProductName() {
        return breedProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.breed_product_name
     *
     * @param breedProductName the value for d_farm.breed_product_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setBreedProductName(String breedProductName) {
        this.breedProductName = breedProductName == null ? null : breedProductName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.breeding_stock
     *
     * @return the value of d_farm.breeding_stock
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Integer getBreedingStock() {
        return breedingStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.breeding_stock
     *
     * @param breedingStock the value for d_farm.breeding_stock
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setBreedingStock(Integer breedingStock) {
        this.breedingStock = breedingStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.male_num
     *
     * @return the value of d_farm.male_num
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Integer getMaleNum() {
        return maleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.male_num
     *
     * @param maleNum the value for d_farm.male_num
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setMaleNum(Integer maleNum) {
        this.maleNum = maleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.female_num
     *
     * @return the value of d_farm.female_num
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Integer getFemaleNum() {
        return femaleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.female_num
     *
     * @param femaleNum the value for d_farm.female_num
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFemaleNum(Integer femaleNum) {
        this.femaleNum = femaleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.out_column
     *
     * @return the value of d_farm.out_column
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getOutColumn() {
        return outColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.out_column
     *
     * @param outColumn the value for d_farm.out_column
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setOutColumn(String outColumn) {
        this.outColumn = outColumn == null ? null : outColumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.is_env_assessment
     *
     * @return the value of d_farm.is_env_assessment
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getIsEnvAssessment() {
        return isEnvAssessment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.is_env_assessment
     *
     * @param isEnvAssessment the value for d_farm.is_env_assessment
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setIsEnvAssessment(String isEnvAssessment) {
        this.isEnvAssessment = isEnvAssessment == null ? null : isEnvAssessment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.facilities_resources
     *
     * @return the value of d_farm.facilities_resources
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getFacilitiesResources() {
        return facilitiesResources;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.facilities_resources
     *
     * @param facilitiesResources the value for d_farm.facilities_resources
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFacilitiesResources(String facilitiesResources) {
        this.facilitiesResources = facilitiesResources == null ? null : facilitiesResources.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.project_name
     *
     * @return the value of d_farm.project_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.project_name
     *
     * @param projectName the value for d_farm.project_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.Improvement_capital
     *
     * @return the value of d_farm.Improvement_capital
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Double getImprovementCapital() {
        return improvementCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.Improvement_capital
     *
     * @param improvementCapital the value for d_farm.Improvement_capital
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setImprovementCapital(Double improvementCapital) {
        this.improvementCapital = improvementCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_farm.farm_summary
     *
     * @return the value of d_farm.farm_summary
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getFarmSummary() {
        return farmSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_farm.farm_summary
     *
     * @param farmSummary the value for d_farm.farm_summary
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFarmSummary(String farmSummary) {
        this.farmSummary = farmSummary == null ? null : farmSummary.trim();
    }
}