package org.clesun.entity;

import java.util.ArrayList;
import java.util.List;

public class DicDistrictExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    protected int offset = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    protected int limit = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public DicDistrictExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setOffset(int offset) {
        this.offset=offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public int getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setLimit(int limit) {
        this.limit=limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public int getLimit() {
        return limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDicIdIsNull() {
            addCriterion("dic_id is null");
            return (Criteria) this;
        }

        public Criteria andDicIdIsNotNull() {
            addCriterion("dic_id is not null");
            return (Criteria) this;
        }

        public Criteria andDicIdEqualTo(Long value) {
            addCriterion("dic_id =", value, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdNotEqualTo(Long value) {
            addCriterion("dic_id <>", value, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdGreaterThan(Long value) {
            addCriterion("dic_id >", value, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdGreaterThanOrEqualTo(Long value) {
            addCriterion("dic_id >=", value, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdLessThan(Long value) {
            addCriterion("dic_id <", value, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdLessThanOrEqualTo(Long value) {
            addCriterion("dic_id <=", value, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdIn(List<Long> values) {
            addCriterion("dic_id in", values, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdNotIn(List<Long> values) {
            addCriterion("dic_id not in", values, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdBetween(Long value1, Long value2) {
            addCriterion("dic_id between", value1, value2, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdNotBetween(Long value1, Long value2) {
            addCriterion("dic_id not between", value1, value2, "dicId");
            return (Criteria) this;
        }

        public Criteria andDistrictNameIsNull() {
            addCriterion("district_name is null");
            return (Criteria) this;
        }

        public Criteria andDistrictNameIsNotNull() {
            addCriterion("district_name is not null");
            return (Criteria) this;
        }

        public Criteria andDistrictNameEqualTo(String value) {
            addCriterion("district_name =", value, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameNotEqualTo(String value) {
            addCriterion("district_name <>", value, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameGreaterThan(String value) {
            addCriterion("district_name >", value, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameGreaterThanOrEqualTo(String value) {
            addCriterion("district_name >=", value, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameLessThan(String value) {
            addCriterion("district_name <", value, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameLessThanOrEqualTo(String value) {
            addCriterion("district_name <=", value, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameLike(String value) {
            addCriterion("district_name like", value, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameNotLike(String value) {
            addCriterion("district_name not like", value, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameIn(List<String> values) {
            addCriterion("district_name in", values, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameNotIn(List<String> values) {
            addCriterion("district_name not in", values, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameBetween(String value1, String value2) {
            addCriterion("district_name between", value1, value2, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictNameNotBetween(String value1, String value2) {
            addCriterion("district_name not between", value1, value2, "districtName");
            return (Criteria) this;
        }

        public Criteria andDistrictPostcodeIsNull() {
            addCriterion("district_postcode is null");
            return (Criteria) this;
        }

        public Criteria andDistrictPostcodeIsNotNull() {
            addCriterion("district_postcode is not null");
            return (Criteria) this;
        }

        public Criteria andDistrictPostcodeEqualTo(String value) {
            addCriterion("district_postcode =", value, "districtPostcode");
            return (Criteria) this;
        }

        public Criteria andDistrictPostcodeNotEqualTo(String value) {
            addCriterion("district_postcode <>", value, "districtPostcode");
            return (Criteria) this;
        }

        public Criteria andDistrictPostcodeGreaterThan(String value) {
            addCriterion("district_postcode >", value, "districtPostcode");
            return (Criteria) this;
        }

        public Criteria andDistrictPostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("district_postcode >=", value, "districtPostcode");
            return (Criteria) this;
        }

        public Criteria andDistrictPostcodeLessThan(String value) {
            addCriterion("district_postcode <", value, "districtPostcode");
            return (Criteria) this;
        }

        public Criteria andDistrictPostcodeLessThanOrEqualTo(String value) {
            addCriterion("district_postcode <=", value, "districtPostcode");
            return (Criteria) this;
        }

        public Criteria andDistrictPostcodeLike(String value) {
            addCriterion("district_postcode like", value, "districtPostcode");
            return (Criteria) this;
        }

        public Criteria andDistrictPostcodeNotLike(String value) {
            addCriterion("district_postcode not like", value, "districtPostcode");
            return (Criteria) this;
        }

        public Criteria andDistrictPostcodeIn(List<String> values) {
            addCriterion("district_postcode in", values, "districtPostcode");
            return (Criteria) this;
        }

        public Criteria andDistrictPostcodeNotIn(List<String> values) {
            addCriterion("district_postcode not in", values, "districtPostcode");
            return (Criteria) this;
        }

        public Criteria andDistrictPostcodeBetween(String value1, String value2) {
            addCriterion("district_postcode between", value1, value2, "districtPostcode");
            return (Criteria) this;
        }

        public Criteria andDistrictPostcodeNotBetween(String value1, String value2) {
            addCriterion("district_postcode not between", value1, value2, "districtPostcode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeIsNull() {
            addCriterion("postal_code is null");
            return (Criteria) this;
        }

        public Criteria andPostalCodeIsNotNull() {
            addCriterion("postal_code is not null");
            return (Criteria) this;
        }

        public Criteria andPostalCodeEqualTo(String value) {
            addCriterion("postal_code =", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeNotEqualTo(String value) {
            addCriterion("postal_code <>", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeGreaterThan(String value) {
            addCriterion("postal_code >", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeGreaterThanOrEqualTo(String value) {
            addCriterion("postal_code >=", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeLessThan(String value) {
            addCriterion("postal_code <", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeLessThanOrEqualTo(String value) {
            addCriterion("postal_code <=", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeLike(String value) {
            addCriterion("postal_code like", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeNotLike(String value) {
            addCriterion("postal_code not like", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeIn(List<String> values) {
            addCriterion("postal_code in", values, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeNotIn(List<String> values) {
            addCriterion("postal_code not in", values, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeBetween(String value1, String value2) {
            addCriterion("postal_code between", value1, value2, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeNotBetween(String value1, String value2) {
            addCriterion("postal_code not between", value1, value2, "postalCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeIsNull() {
            addCriterion("province_code is null");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeIsNotNull() {
            addCriterion("province_code is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeEqualTo(String value) {
            addCriterion("province_code =", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotEqualTo(String value) {
            addCriterion("province_code <>", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeGreaterThan(String value) {
            addCriterion("province_code >", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeGreaterThanOrEqualTo(String value) {
            addCriterion("province_code >=", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeLessThan(String value) {
            addCriterion("province_code <", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeLessThanOrEqualTo(String value) {
            addCriterion("province_code <=", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeLike(String value) {
            addCriterion("province_code like", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotLike(String value) {
            addCriterion("province_code not like", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeIn(List<String> values) {
            addCriterion("province_code in", values, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotIn(List<String> values) {
            addCriterion("province_code not in", values, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeBetween(String value1, String value2) {
            addCriterion("province_code between", value1, value2, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotBetween(String value1, String value2) {
            addCriterion("province_code not between", value1, value2, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeIsNull() {
            addCriterion("district_code is null");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeIsNotNull() {
            addCriterion("district_code is not null");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeEqualTo(String value) {
            addCriterion("district_code =", value, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeNotEqualTo(String value) {
            addCriterion("district_code <>", value, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeGreaterThan(String value) {
            addCriterion("district_code >", value, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeGreaterThanOrEqualTo(String value) {
            addCriterion("district_code >=", value, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeLessThan(String value) {
            addCriterion("district_code <", value, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeLessThanOrEqualTo(String value) {
            addCriterion("district_code <=", value, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeLike(String value) {
            addCriterion("district_code like", value, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeNotLike(String value) {
            addCriterion("district_code not like", value, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeIn(List<String> values) {
            addCriterion("district_code in", values, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeNotIn(List<String> values) {
            addCriterion("district_code not in", values, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeBetween(String value1, String value2) {
            addCriterion("district_code between", value1, value2, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeNotBetween(String value1, String value2) {
            addCriterion("district_code not between", value1, value2, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictLatIsNull() {
            addCriterion("district_lat is null");
            return (Criteria) this;
        }

        public Criteria andDistrictLatIsNotNull() {
            addCriterion("district_lat is not null");
            return (Criteria) this;
        }

        public Criteria andDistrictLatEqualTo(Double value) {
            addCriterion("district_lat =", value, "districtLat");
            return (Criteria) this;
        }

        public Criteria andDistrictLatNotEqualTo(Double value) {
            addCriterion("district_lat <>", value, "districtLat");
            return (Criteria) this;
        }

        public Criteria andDistrictLatGreaterThan(Double value) {
            addCriterion("district_lat >", value, "districtLat");
            return (Criteria) this;
        }

        public Criteria andDistrictLatGreaterThanOrEqualTo(Double value) {
            addCriterion("district_lat >=", value, "districtLat");
            return (Criteria) this;
        }

        public Criteria andDistrictLatLessThan(Double value) {
            addCriterion("district_lat <", value, "districtLat");
            return (Criteria) this;
        }

        public Criteria andDistrictLatLessThanOrEqualTo(Double value) {
            addCriterion("district_lat <=", value, "districtLat");
            return (Criteria) this;
        }

        public Criteria andDistrictLatIn(List<Double> values) {
            addCriterion("district_lat in", values, "districtLat");
            return (Criteria) this;
        }

        public Criteria andDistrictLatNotIn(List<Double> values) {
            addCriterion("district_lat not in", values, "districtLat");
            return (Criteria) this;
        }

        public Criteria andDistrictLatBetween(Double value1, Double value2) {
            addCriterion("district_lat between", value1, value2, "districtLat");
            return (Criteria) this;
        }

        public Criteria andDistrictLatNotBetween(Double value1, Double value2) {
            addCriterion("district_lat not between", value1, value2, "districtLat");
            return (Criteria) this;
        }

        public Criteria andDistrictLngIsNull() {
            addCriterion("district_lng is null");
            return (Criteria) this;
        }

        public Criteria andDistrictLngIsNotNull() {
            addCriterion("district_lng is not null");
            return (Criteria) this;
        }

        public Criteria andDistrictLngEqualTo(Double value) {
            addCriterion("district_lng =", value, "districtLng");
            return (Criteria) this;
        }

        public Criteria andDistrictLngNotEqualTo(Double value) {
            addCriterion("district_lng <>", value, "districtLng");
            return (Criteria) this;
        }

        public Criteria andDistrictLngGreaterThan(Double value) {
            addCriterion("district_lng >", value, "districtLng");
            return (Criteria) this;
        }

        public Criteria andDistrictLngGreaterThanOrEqualTo(Double value) {
            addCriterion("district_lng >=", value, "districtLng");
            return (Criteria) this;
        }

        public Criteria andDistrictLngLessThan(Double value) {
            addCriterion("district_lng <", value, "districtLng");
            return (Criteria) this;
        }

        public Criteria andDistrictLngLessThanOrEqualTo(Double value) {
            addCriterion("district_lng <=", value, "districtLng");
            return (Criteria) this;
        }

        public Criteria andDistrictLngIn(List<Double> values) {
            addCriterion("district_lng in", values, "districtLng");
            return (Criteria) this;
        }

        public Criteria andDistrictLngNotIn(List<Double> values) {
            addCriterion("district_lng not in", values, "districtLng");
            return (Criteria) this;
        }

        public Criteria andDistrictLngBetween(Double value1, Double value2) {
            addCriterion("district_lng between", value1, value2, "districtLng");
            return (Criteria) this;
        }

        public Criteria andDistrictLngNotBetween(Double value1, Double value2) {
            addCriterion("district_lng not between", value1, value2, "districtLng");
            return (Criteria) this;
        }

        public Criteria andParentCodeIsNull() {
            addCriterion("parent_code is null");
            return (Criteria) this;
        }

        public Criteria andParentCodeIsNotNull() {
            addCriterion("parent_code is not null");
            return (Criteria) this;
        }

        public Criteria andParentCodeEqualTo(Long value) {
            addCriterion("parent_code =", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeNotEqualTo(Long value) {
            addCriterion("parent_code <>", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeGreaterThan(Long value) {
            addCriterion("parent_code >", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("parent_code >=", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeLessThan(Long value) {
            addCriterion("parent_code <", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeLessThanOrEqualTo(Long value) {
            addCriterion("parent_code <=", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeIn(List<Long> values) {
            addCriterion("parent_code in", values, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeNotIn(List<Long> values) {
            addCriterion("parent_code not in", values, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeBetween(Long value1, Long value2) {
            addCriterion("parent_code between", value1, value2, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeNotBetween(Long value1, Long value2) {
            addCriterion("parent_code not between", value1, value2, "parentCode");
            return (Criteria) this;
        }

        public Criteria andDistrictLevelIsNull() {
            addCriterion("district_level is null");
            return (Criteria) this;
        }

        public Criteria andDistrictLevelIsNotNull() {
            addCriterion("district_level is not null");
            return (Criteria) this;
        }

        public Criteria andDistrictLevelEqualTo(Integer value) {
            addCriterion("district_level =", value, "districtLevel");
            return (Criteria) this;
        }

        public Criteria andDistrictLevelNotEqualTo(Integer value) {
            addCriterion("district_level <>", value, "districtLevel");
            return (Criteria) this;
        }

        public Criteria andDistrictLevelGreaterThan(Integer value) {
            addCriterion("district_level >", value, "districtLevel");
            return (Criteria) this;
        }

        public Criteria andDistrictLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("district_level >=", value, "districtLevel");
            return (Criteria) this;
        }

        public Criteria andDistrictLevelLessThan(Integer value) {
            addCriterion("district_level <", value, "districtLevel");
            return (Criteria) this;
        }

        public Criteria andDistrictLevelLessThanOrEqualTo(Integer value) {
            addCriterion("district_level <=", value, "districtLevel");
            return (Criteria) this;
        }

        public Criteria andDistrictLevelIn(List<Integer> values) {
            addCriterion("district_level in", values, "districtLevel");
            return (Criteria) this;
        }

        public Criteria andDistrictLevelNotIn(List<Integer> values) {
            addCriterion("district_level not in", values, "districtLevel");
            return (Criteria) this;
        }

        public Criteria andDistrictLevelBetween(Integer value1, Integer value2) {
            addCriterion("district_level between", value1, value2, "districtLevel");
            return (Criteria) this;
        }

        public Criteria andDistrictLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("district_level not between", value1, value2, "districtLevel");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Integer value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Integer value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Integer value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Integer value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Integer value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Integer> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Integer> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Integer value1, Integer value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andDicRemarkIsNull() {
            addCriterion("dic_remark is null");
            return (Criteria) this;
        }

        public Criteria andDicRemarkIsNotNull() {
            addCriterion("dic_remark is not null");
            return (Criteria) this;
        }

        public Criteria andDicRemarkEqualTo(String value) {
            addCriterion("dic_remark =", value, "dicRemark");
            return (Criteria) this;
        }

        public Criteria andDicRemarkNotEqualTo(String value) {
            addCriterion("dic_remark <>", value, "dicRemark");
            return (Criteria) this;
        }

        public Criteria andDicRemarkGreaterThan(String value) {
            addCriterion("dic_remark >", value, "dicRemark");
            return (Criteria) this;
        }

        public Criteria andDicRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("dic_remark >=", value, "dicRemark");
            return (Criteria) this;
        }

        public Criteria andDicRemarkLessThan(String value) {
            addCriterion("dic_remark <", value, "dicRemark");
            return (Criteria) this;
        }

        public Criteria andDicRemarkLessThanOrEqualTo(String value) {
            addCriterion("dic_remark <=", value, "dicRemark");
            return (Criteria) this;
        }

        public Criteria andDicRemarkLike(String value) {
            addCriterion("dic_remark like", value, "dicRemark");
            return (Criteria) this;
        }

        public Criteria andDicRemarkNotLike(String value) {
            addCriterion("dic_remark not like", value, "dicRemark");
            return (Criteria) this;
        }

        public Criteria andDicRemarkIn(List<String> values) {
            addCriterion("dic_remark in", values, "dicRemark");
            return (Criteria) this;
        }

        public Criteria andDicRemarkNotIn(List<String> values) {
            addCriterion("dic_remark not in", values, "dicRemark");
            return (Criteria) this;
        }

        public Criteria andDicRemarkBetween(String value1, String value2) {
            addCriterion("dic_remark between", value1, value2, "dicRemark");
            return (Criteria) this;
        }

        public Criteria andDicRemarkNotBetween(String value1, String value2) {
            addCriterion("dic_remark not between", value1, value2, "dicRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dic_district
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 17 16:38:55 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}