package org.clesun.entity;

public class DicDistrict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_district.dic_id
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private Long dicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_district.district_name
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String districtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_district.district_postcode
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String districtPostcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_district.postal_code
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String postalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_district.province_code
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_district.district_code
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String districtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_district.district_lat
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private Double districtLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_district.district_lng
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private Double districtLng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_district.parent_code
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private Long parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_district.district_level
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private Integer districtLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_district.is_delete
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_district.dic_remark
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String dicRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_district.district_polygon
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String districtPolygon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_district.dic_id
     *
     * @return the value of dic_district.dic_id
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public Long getDicId() {
        return dicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_district.dic_id
     *
     * @param dicId the value for dic_district.dic_id
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setDicId(Long dicId) {
        this.dicId = dicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_district.district_name
     *
     * @return the value of dic_district.district_name
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_district.district_name
     *
     * @param districtName the value for dic_district.district_name
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_district.district_postcode
     *
     * @return the value of dic_district.district_postcode
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getDistrictPostcode() {
        return districtPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_district.district_postcode
     *
     * @param districtPostcode the value for dic_district.district_postcode
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setDistrictPostcode(String districtPostcode) {
        this.districtPostcode = districtPostcode == null ? null : districtPostcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_district.postal_code
     *
     * @return the value of dic_district.postal_code
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_district.postal_code
     *
     * @param postalCode the value for dic_district.postal_code
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode == null ? null : postalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_district.province_code
     *
     * @return the value of dic_district.province_code
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_district.province_code
     *
     * @param provinceCode the value for dic_district.province_code
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_district.district_code
     *
     * @return the value of dic_district.district_code
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_district.district_code
     *
     * @param districtCode the value for dic_district.district_code
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode == null ? null : districtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_district.district_lat
     *
     * @return the value of dic_district.district_lat
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public Double getDistrictLat() {
        return districtLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_district.district_lat
     *
     * @param districtLat the value for dic_district.district_lat
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setDistrictLat(Double districtLat) {
        this.districtLat = districtLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_district.district_lng
     *
     * @return the value of dic_district.district_lng
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public Double getDistrictLng() {
        return districtLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_district.district_lng
     *
     * @param districtLng the value for dic_district.district_lng
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setDistrictLng(Double districtLng) {
        this.districtLng = districtLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_district.parent_code
     *
     * @return the value of dic_district.parent_code
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public Long getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_district.parent_code
     *
     * @param parentCode the value for dic_district.parent_code
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setParentCode(Long parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_district.district_level
     *
     * @return the value of dic_district.district_level
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public Integer getDistrictLevel() {
        return districtLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_district.district_level
     *
     * @param districtLevel the value for dic_district.district_level
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setDistrictLevel(Integer districtLevel) {
        this.districtLevel = districtLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_district.is_delete
     *
     * @return the value of dic_district.is_delete
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_district.is_delete
     *
     * @param isDelete the value for dic_district.is_delete
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_district.dic_remark
     *
     * @return the value of dic_district.dic_remark
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getDicRemark() {
        return dicRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_district.dic_remark
     *
     * @param dicRemark the value for dic_district.dic_remark
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setDicRemark(String dicRemark) {
        this.dicRemark = dicRemark == null ? null : dicRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_district.district_polygon
     *
     * @return the value of dic_district.district_polygon
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getDistrictPolygon() {
        return districtPolygon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_district.district_polygon
     *
     * @param districtPolygon the value for dic_district.district_polygon
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setDistrictPolygon(String districtPolygon) {
        this.districtPolygon = districtPolygon == null ? null : districtPolygon.trim();
    }
}