package org.clesun.entity;

public class DicSys {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_sys.dic_id
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private Long dicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_sys.parent_id
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_sys.dic_key
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String dicKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_sys.dic_value
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String dicValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_sys.dic_type
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private Integer dicType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_sys.ref_table
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String refTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_sys.ref_id
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private Long refId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_sys.dic_remark
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String dicRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_sys.dic_id
     *
     * @return the value of dic_sys.dic_id
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public Long getDicId() {
        return dicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_sys.dic_id
     *
     * @param dicId the value for dic_sys.dic_id
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setDicId(Long dicId) {
        this.dicId = dicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_sys.parent_id
     *
     * @return the value of dic_sys.parent_id
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_sys.parent_id
     *
     * @param parentId the value for dic_sys.parent_id
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_sys.dic_key
     *
     * @return the value of dic_sys.dic_key
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getDicKey() {
        return dicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_sys.dic_key
     *
     * @param dicKey the value for dic_sys.dic_key
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setDicKey(String dicKey) {
        this.dicKey = dicKey == null ? null : dicKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_sys.dic_value
     *
     * @return the value of dic_sys.dic_value
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getDicValue() {
        return dicValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_sys.dic_value
     *
     * @param dicValue the value for dic_sys.dic_value
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setDicValue(String dicValue) {
        this.dicValue = dicValue == null ? null : dicValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_sys.dic_type
     *
     * @return the value of dic_sys.dic_type
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public Integer getDicType() {
        return dicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_sys.dic_type
     *
     * @param dicType the value for dic_sys.dic_type
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setDicType(Integer dicType) {
        this.dicType = dicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_sys.ref_table
     *
     * @return the value of dic_sys.ref_table
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getRefTable() {
        return refTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_sys.ref_table
     *
     * @param refTable the value for dic_sys.ref_table
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setRefTable(String refTable) {
        this.refTable = refTable == null ? null : refTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_sys.ref_id
     *
     * @return the value of dic_sys.ref_id
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public Long getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_sys.ref_id
     *
     * @param refId the value for dic_sys.ref_id
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setRefId(Long refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_sys.dic_remark
     *
     * @return the value of dic_sys.dic_remark
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getDicRemark() {
        return dicRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_sys.dic_remark
     *
     * @param dicRemark the value for dic_sys.dic_remark
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setDicRemark(String dicRemark) {
        this.dicRemark = dicRemark == null ? null : dicRemark.trim();
    }
}