package org.clesun.entity;

import java.util.Date;

public class DProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.product_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.product_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.product_parent_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Long productParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.product_parent_value
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String productParentValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.product_type
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Integer productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.total_yield
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Double totalYield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.yield_unit
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String yieldUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.product_price
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Double productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.price_unit
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String priceUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.sold_quantity
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Double soldQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.farm_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Long farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.farm_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String farmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.sold_time
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Date soldTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.create_time
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.year
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.month
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.day
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.province
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.city
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.county
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.remark
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.price_release_time
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private Date priceReleaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_product.place_origin
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    private String placeOrigin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.product_id
     *
     * @return the value of d_product.product_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.product_id
     *
     * @param productId the value for d_product.product_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.product_name
     *
     * @return the value of d_product.product_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.product_name
     *
     * @param productName the value for d_product.product_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.product_parent_id
     *
     * @return the value of d_product.product_parent_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Long getProductParentId() {
        return productParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.product_parent_id
     *
     * @param productParentId the value for d_product.product_parent_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setProductParentId(Long productParentId) {
        this.productParentId = productParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.product_parent_value
     *
     * @return the value of d_product.product_parent_value
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getProductParentValue() {
        return productParentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.product_parent_value
     *
     * @param productParentValue the value for d_product.product_parent_value
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setProductParentValue(String productParentValue) {
        this.productParentValue = productParentValue == null ? null : productParentValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.product_type
     *
     * @return the value of d_product.product_type
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.product_type
     *
     * @param productType the value for d_product.product_type
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.total_yield
     *
     * @return the value of d_product.total_yield
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Double getTotalYield() {
        return totalYield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.total_yield
     *
     * @param totalYield the value for d_product.total_yield
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setTotalYield(Double totalYield) {
        this.totalYield = totalYield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.yield_unit
     *
     * @return the value of d_product.yield_unit
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getYieldUnit() {
        return yieldUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.yield_unit
     *
     * @param yieldUnit the value for d_product.yield_unit
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setYieldUnit(String yieldUnit) {
        this.yieldUnit = yieldUnit == null ? null : yieldUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.product_price
     *
     * @return the value of d_product.product_price
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Double getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.product_price
     *
     * @param productPrice the value for d_product.product_price
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setProductPrice(Double productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.price_unit
     *
     * @return the value of d_product.price_unit
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getPriceUnit() {
        return priceUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.price_unit
     *
     * @param priceUnit the value for d_product.price_unit
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setPriceUnit(String priceUnit) {
        this.priceUnit = priceUnit == null ? null : priceUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.sold_quantity
     *
     * @return the value of d_product.sold_quantity
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Double getSoldQuantity() {
        return soldQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.sold_quantity
     *
     * @param soldQuantity the value for d_product.sold_quantity
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setSoldQuantity(Double soldQuantity) {
        this.soldQuantity = soldQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.farm_id
     *
     * @return the value of d_product.farm_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Long getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.farm_id
     *
     * @param farmId the value for d_product.farm_id
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFarmId(Long farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.farm_name
     *
     * @return the value of d_product.farm_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getFarmName() {
        return farmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.farm_name
     *
     * @param farmName the value for d_product.farm_name
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setFarmName(String farmName) {
        this.farmName = farmName == null ? null : farmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.sold_time
     *
     * @return the value of d_product.sold_time
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Date getSoldTime() {
        return soldTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.sold_time
     *
     * @param soldTime the value for d_product.sold_time
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setSoldTime(Date soldTime) {
        this.soldTime = soldTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.create_time
     *
     * @return the value of d_product.create_time
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.create_time
     *
     * @param createTime the value for d_product.create_time
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.year
     *
     * @return the value of d_product.year
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.year
     *
     * @param year the value for d_product.year
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.month
     *
     * @return the value of d_product.month
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.month
     *
     * @param month the value for d_product.month
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.day
     *
     * @return the value of d_product.day
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.day
     *
     * @param day the value for d_product.day
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setDay(String day) {
        this.day = day == null ? null : day.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.province
     *
     * @return the value of d_product.province
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.province
     *
     * @param province the value for d_product.province
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.city
     *
     * @return the value of d_product.city
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.city
     *
     * @param city the value for d_product.city
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.county
     *
     * @return the value of d_product.county
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.county
     *
     * @param county the value for d_product.county
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.remark
     *
     * @return the value of d_product.remark
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.remark
     *
     * @param remark the value for d_product.remark
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.price_release_time
     *
     * @return the value of d_product.price_release_time
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Date getPriceReleaseTime() {
        return priceReleaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.price_release_time
     *
     * @param priceReleaseTime the value for d_product.price_release_time
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setPriceReleaseTime(Date priceReleaseTime) {
        this.priceReleaseTime = priceReleaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_product.place_origin
     *
     * @return the value of d_product.place_origin
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getPlaceOrigin() {
        return placeOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_product.place_origin
     *
     * @param placeOrigin the value for d_product.place_origin
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setPlaceOrigin(String placeOrigin) {
        this.placeOrigin = placeOrigin == null ? null : placeOrigin.trim();
    }
}