package org.clesun.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    protected int offset = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    protected int limit = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public DProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setOffset(int offset) {
        this.offset=offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public int getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public void setLimit(int limit) {
        this.limit=limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public int getLimit() {
        return limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Long value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Long value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Long value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Long value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Long value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Long value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Long> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Long> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Long value1, Long value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Long value1, Long value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductParentIdIsNull() {
            addCriterion("product_parent_id is null");
            return (Criteria) this;
        }

        public Criteria andProductParentIdIsNotNull() {
            addCriterion("product_parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductParentIdEqualTo(Long value) {
            addCriterion("product_parent_id =", value, "productParentId");
            return (Criteria) this;
        }

        public Criteria andProductParentIdNotEqualTo(Long value) {
            addCriterion("product_parent_id <>", value, "productParentId");
            return (Criteria) this;
        }

        public Criteria andProductParentIdGreaterThan(Long value) {
            addCriterion("product_parent_id >", value, "productParentId");
            return (Criteria) this;
        }

        public Criteria andProductParentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("product_parent_id >=", value, "productParentId");
            return (Criteria) this;
        }

        public Criteria andProductParentIdLessThan(Long value) {
            addCriterion("product_parent_id <", value, "productParentId");
            return (Criteria) this;
        }

        public Criteria andProductParentIdLessThanOrEqualTo(Long value) {
            addCriterion("product_parent_id <=", value, "productParentId");
            return (Criteria) this;
        }

        public Criteria andProductParentIdIn(List<Long> values) {
            addCriterion("product_parent_id in", values, "productParentId");
            return (Criteria) this;
        }

        public Criteria andProductParentIdNotIn(List<Long> values) {
            addCriterion("product_parent_id not in", values, "productParentId");
            return (Criteria) this;
        }

        public Criteria andProductParentIdBetween(Long value1, Long value2) {
            addCriterion("product_parent_id between", value1, value2, "productParentId");
            return (Criteria) this;
        }

        public Criteria andProductParentIdNotBetween(Long value1, Long value2) {
            addCriterion("product_parent_id not between", value1, value2, "productParentId");
            return (Criteria) this;
        }

        public Criteria andProductParentValueIsNull() {
            addCriterion("product_parent_value is null");
            return (Criteria) this;
        }

        public Criteria andProductParentValueIsNotNull() {
            addCriterion("product_parent_value is not null");
            return (Criteria) this;
        }

        public Criteria andProductParentValueEqualTo(String value) {
            addCriterion("product_parent_value =", value, "productParentValue");
            return (Criteria) this;
        }

        public Criteria andProductParentValueNotEqualTo(String value) {
            addCriterion("product_parent_value <>", value, "productParentValue");
            return (Criteria) this;
        }

        public Criteria andProductParentValueGreaterThan(String value) {
            addCriterion("product_parent_value >", value, "productParentValue");
            return (Criteria) this;
        }

        public Criteria andProductParentValueGreaterThanOrEqualTo(String value) {
            addCriterion("product_parent_value >=", value, "productParentValue");
            return (Criteria) this;
        }

        public Criteria andProductParentValueLessThan(String value) {
            addCriterion("product_parent_value <", value, "productParentValue");
            return (Criteria) this;
        }

        public Criteria andProductParentValueLessThanOrEqualTo(String value) {
            addCriterion("product_parent_value <=", value, "productParentValue");
            return (Criteria) this;
        }

        public Criteria andProductParentValueLike(String value) {
            addCriterion("product_parent_value like", value, "productParentValue");
            return (Criteria) this;
        }

        public Criteria andProductParentValueNotLike(String value) {
            addCriterion("product_parent_value not like", value, "productParentValue");
            return (Criteria) this;
        }

        public Criteria andProductParentValueIn(List<String> values) {
            addCriterion("product_parent_value in", values, "productParentValue");
            return (Criteria) this;
        }

        public Criteria andProductParentValueNotIn(List<String> values) {
            addCriterion("product_parent_value not in", values, "productParentValue");
            return (Criteria) this;
        }

        public Criteria andProductParentValueBetween(String value1, String value2) {
            addCriterion("product_parent_value between", value1, value2, "productParentValue");
            return (Criteria) this;
        }

        public Criteria andProductParentValueNotBetween(String value1, String value2) {
            addCriterion("product_parent_value not between", value1, value2, "productParentValue");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNull() {
            addCriterion("product_type is null");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNotNull() {
            addCriterion("product_type is not null");
            return (Criteria) this;
        }

        public Criteria andProductTypeEqualTo(Integer value) {
            addCriterion("product_type =", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotEqualTo(Integer value) {
            addCriterion("product_type <>", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThan(Integer value) {
            addCriterion("product_type >", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_type >=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThan(Integer value) {
            addCriterion("product_type <", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThanOrEqualTo(Integer value) {
            addCriterion("product_type <=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeIn(List<Integer> values) {
            addCriterion("product_type in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotIn(List<Integer> values) {
            addCriterion("product_type not in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeBetween(Integer value1, Integer value2) {
            addCriterion("product_type between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("product_type not between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andTotalYieldIsNull() {
            addCriterion("total_yield is null");
            return (Criteria) this;
        }

        public Criteria andTotalYieldIsNotNull() {
            addCriterion("total_yield is not null");
            return (Criteria) this;
        }

        public Criteria andTotalYieldEqualTo(Double value) {
            addCriterion("total_yield =", value, "totalYield");
            return (Criteria) this;
        }

        public Criteria andTotalYieldNotEqualTo(Double value) {
            addCriterion("total_yield <>", value, "totalYield");
            return (Criteria) this;
        }

        public Criteria andTotalYieldGreaterThan(Double value) {
            addCriterion("total_yield >", value, "totalYield");
            return (Criteria) this;
        }

        public Criteria andTotalYieldGreaterThanOrEqualTo(Double value) {
            addCriterion("total_yield >=", value, "totalYield");
            return (Criteria) this;
        }

        public Criteria andTotalYieldLessThan(Double value) {
            addCriterion("total_yield <", value, "totalYield");
            return (Criteria) this;
        }

        public Criteria andTotalYieldLessThanOrEqualTo(Double value) {
            addCriterion("total_yield <=", value, "totalYield");
            return (Criteria) this;
        }

        public Criteria andTotalYieldIn(List<Double> values) {
            addCriterion("total_yield in", values, "totalYield");
            return (Criteria) this;
        }

        public Criteria andTotalYieldNotIn(List<Double> values) {
            addCriterion("total_yield not in", values, "totalYield");
            return (Criteria) this;
        }

        public Criteria andTotalYieldBetween(Double value1, Double value2) {
            addCriterion("total_yield between", value1, value2, "totalYield");
            return (Criteria) this;
        }

        public Criteria andTotalYieldNotBetween(Double value1, Double value2) {
            addCriterion("total_yield not between", value1, value2, "totalYield");
            return (Criteria) this;
        }

        public Criteria andYieldUnitIsNull() {
            addCriterion("yield_unit is null");
            return (Criteria) this;
        }

        public Criteria andYieldUnitIsNotNull() {
            addCriterion("yield_unit is not null");
            return (Criteria) this;
        }

        public Criteria andYieldUnitEqualTo(String value) {
            addCriterion("yield_unit =", value, "yieldUnit");
            return (Criteria) this;
        }

        public Criteria andYieldUnitNotEqualTo(String value) {
            addCriterion("yield_unit <>", value, "yieldUnit");
            return (Criteria) this;
        }

        public Criteria andYieldUnitGreaterThan(String value) {
            addCriterion("yield_unit >", value, "yieldUnit");
            return (Criteria) this;
        }

        public Criteria andYieldUnitGreaterThanOrEqualTo(String value) {
            addCriterion("yield_unit >=", value, "yieldUnit");
            return (Criteria) this;
        }

        public Criteria andYieldUnitLessThan(String value) {
            addCriterion("yield_unit <", value, "yieldUnit");
            return (Criteria) this;
        }

        public Criteria andYieldUnitLessThanOrEqualTo(String value) {
            addCriterion("yield_unit <=", value, "yieldUnit");
            return (Criteria) this;
        }

        public Criteria andYieldUnitLike(String value) {
            addCriterion("yield_unit like", value, "yieldUnit");
            return (Criteria) this;
        }

        public Criteria andYieldUnitNotLike(String value) {
            addCriterion("yield_unit not like", value, "yieldUnit");
            return (Criteria) this;
        }

        public Criteria andYieldUnitIn(List<String> values) {
            addCriterion("yield_unit in", values, "yieldUnit");
            return (Criteria) this;
        }

        public Criteria andYieldUnitNotIn(List<String> values) {
            addCriterion("yield_unit not in", values, "yieldUnit");
            return (Criteria) this;
        }

        public Criteria andYieldUnitBetween(String value1, String value2) {
            addCriterion("yield_unit between", value1, value2, "yieldUnit");
            return (Criteria) this;
        }

        public Criteria andYieldUnitNotBetween(String value1, String value2) {
            addCriterion("yield_unit not between", value1, value2, "yieldUnit");
            return (Criteria) this;
        }

        public Criteria andProductPriceIsNull() {
            addCriterion("product_price is null");
            return (Criteria) this;
        }

        public Criteria andProductPriceIsNotNull() {
            addCriterion("product_price is not null");
            return (Criteria) this;
        }

        public Criteria andProductPriceEqualTo(Double value) {
            addCriterion("product_price =", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotEqualTo(Double value) {
            addCriterion("product_price <>", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceGreaterThan(Double value) {
            addCriterion("product_price >", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("product_price >=", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceLessThan(Double value) {
            addCriterion("product_price <", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceLessThanOrEqualTo(Double value) {
            addCriterion("product_price <=", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceIn(List<Double> values) {
            addCriterion("product_price in", values, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotIn(List<Double> values) {
            addCriterion("product_price not in", values, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceBetween(Double value1, Double value2) {
            addCriterion("product_price between", value1, value2, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotBetween(Double value1, Double value2) {
            addCriterion("product_price not between", value1, value2, "productPrice");
            return (Criteria) this;
        }

        public Criteria andPriceUnitIsNull() {
            addCriterion("price_unit is null");
            return (Criteria) this;
        }

        public Criteria andPriceUnitIsNotNull() {
            addCriterion("price_unit is not null");
            return (Criteria) this;
        }

        public Criteria andPriceUnitEqualTo(String value) {
            addCriterion("price_unit =", value, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitNotEqualTo(String value) {
            addCriterion("price_unit <>", value, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitGreaterThan(String value) {
            addCriterion("price_unit >", value, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitGreaterThanOrEqualTo(String value) {
            addCriterion("price_unit >=", value, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitLessThan(String value) {
            addCriterion("price_unit <", value, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitLessThanOrEqualTo(String value) {
            addCriterion("price_unit <=", value, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitLike(String value) {
            addCriterion("price_unit like", value, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitNotLike(String value) {
            addCriterion("price_unit not like", value, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitIn(List<String> values) {
            addCriterion("price_unit in", values, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitNotIn(List<String> values) {
            addCriterion("price_unit not in", values, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitBetween(String value1, String value2) {
            addCriterion("price_unit between", value1, value2, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andPriceUnitNotBetween(String value1, String value2) {
            addCriterion("price_unit not between", value1, value2, "priceUnit");
            return (Criteria) this;
        }

        public Criteria andSoldQuantityIsNull() {
            addCriterion("sold_quantity is null");
            return (Criteria) this;
        }

        public Criteria andSoldQuantityIsNotNull() {
            addCriterion("sold_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andSoldQuantityEqualTo(Double value) {
            addCriterion("sold_quantity =", value, "soldQuantity");
            return (Criteria) this;
        }

        public Criteria andSoldQuantityNotEqualTo(Double value) {
            addCriterion("sold_quantity <>", value, "soldQuantity");
            return (Criteria) this;
        }

        public Criteria andSoldQuantityGreaterThan(Double value) {
            addCriterion("sold_quantity >", value, "soldQuantity");
            return (Criteria) this;
        }

        public Criteria andSoldQuantityGreaterThanOrEqualTo(Double value) {
            addCriterion("sold_quantity >=", value, "soldQuantity");
            return (Criteria) this;
        }

        public Criteria andSoldQuantityLessThan(Double value) {
            addCriterion("sold_quantity <", value, "soldQuantity");
            return (Criteria) this;
        }

        public Criteria andSoldQuantityLessThanOrEqualTo(Double value) {
            addCriterion("sold_quantity <=", value, "soldQuantity");
            return (Criteria) this;
        }

        public Criteria andSoldQuantityIn(List<Double> values) {
            addCriterion("sold_quantity in", values, "soldQuantity");
            return (Criteria) this;
        }

        public Criteria andSoldQuantityNotIn(List<Double> values) {
            addCriterion("sold_quantity not in", values, "soldQuantity");
            return (Criteria) this;
        }

        public Criteria andSoldQuantityBetween(Double value1, Double value2) {
            addCriterion("sold_quantity between", value1, value2, "soldQuantity");
            return (Criteria) this;
        }

        public Criteria andSoldQuantityNotBetween(Double value1, Double value2) {
            addCriterion("sold_quantity not between", value1, value2, "soldQuantity");
            return (Criteria) this;
        }

        public Criteria andFarmIdIsNull() {
            addCriterion("farm_id is null");
            return (Criteria) this;
        }

        public Criteria andFarmIdIsNotNull() {
            addCriterion("farm_id is not null");
            return (Criteria) this;
        }

        public Criteria andFarmIdEqualTo(Long value) {
            addCriterion("farm_id =", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdNotEqualTo(Long value) {
            addCriterion("farm_id <>", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdGreaterThan(Long value) {
            addCriterion("farm_id >", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdGreaterThanOrEqualTo(Long value) {
            addCriterion("farm_id >=", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdLessThan(Long value) {
            addCriterion("farm_id <", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdLessThanOrEqualTo(Long value) {
            addCriterion("farm_id <=", value, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdIn(List<Long> values) {
            addCriterion("farm_id in", values, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdNotIn(List<Long> values) {
            addCriterion("farm_id not in", values, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdBetween(Long value1, Long value2) {
            addCriterion("farm_id between", value1, value2, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmIdNotBetween(Long value1, Long value2) {
            addCriterion("farm_id not between", value1, value2, "farmId");
            return (Criteria) this;
        }

        public Criteria andFarmNameIsNull() {
            addCriterion("farm_name is null");
            return (Criteria) this;
        }

        public Criteria andFarmNameIsNotNull() {
            addCriterion("farm_name is not null");
            return (Criteria) this;
        }

        public Criteria andFarmNameEqualTo(String value) {
            addCriterion("farm_name =", value, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameNotEqualTo(String value) {
            addCriterion("farm_name <>", value, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameGreaterThan(String value) {
            addCriterion("farm_name >", value, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameGreaterThanOrEqualTo(String value) {
            addCriterion("farm_name >=", value, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameLessThan(String value) {
            addCriterion("farm_name <", value, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameLessThanOrEqualTo(String value) {
            addCriterion("farm_name <=", value, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameLike(String value) {
            addCriterion("farm_name like", value, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameNotLike(String value) {
            addCriterion("farm_name not like", value, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameIn(List<String> values) {
            addCriterion("farm_name in", values, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameNotIn(List<String> values) {
            addCriterion("farm_name not in", values, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameBetween(String value1, String value2) {
            addCriterion("farm_name between", value1, value2, "farmName");
            return (Criteria) this;
        }

        public Criteria andFarmNameNotBetween(String value1, String value2) {
            addCriterion("farm_name not between", value1, value2, "farmName");
            return (Criteria) this;
        }

        public Criteria andSoldTimeIsNull() {
            addCriterion("sold_time is null");
            return (Criteria) this;
        }

        public Criteria andSoldTimeIsNotNull() {
            addCriterion("sold_time is not null");
            return (Criteria) this;
        }

        public Criteria andSoldTimeEqualTo(Date value) {
            addCriterion("sold_time =", value, "soldTime");
            return (Criteria) this;
        }

        public Criteria andSoldTimeNotEqualTo(Date value) {
            addCriterion("sold_time <>", value, "soldTime");
            return (Criteria) this;
        }

        public Criteria andSoldTimeGreaterThan(Date value) {
            addCriterion("sold_time >", value, "soldTime");
            return (Criteria) this;
        }

        public Criteria andSoldTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sold_time >=", value, "soldTime");
            return (Criteria) this;
        }

        public Criteria andSoldTimeLessThan(Date value) {
            addCriterion("sold_time <", value, "soldTime");
            return (Criteria) this;
        }

        public Criteria andSoldTimeLessThanOrEqualTo(Date value) {
            addCriterion("sold_time <=", value, "soldTime");
            return (Criteria) this;
        }

        public Criteria andSoldTimeIn(List<Date> values) {
            addCriterion("sold_time in", values, "soldTime");
            return (Criteria) this;
        }

        public Criteria andSoldTimeNotIn(List<Date> values) {
            addCriterion("sold_time not in", values, "soldTime");
            return (Criteria) this;
        }

        public Criteria andSoldTimeBetween(Date value1, Date value2) {
            addCriterion("sold_time between", value1, value2, "soldTime");
            return (Criteria) this;
        }

        public Criteria andSoldTimeNotBetween(Date value1, Date value2) {
            addCriterion("sold_time not between", value1, value2, "soldTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("year is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("year is not null");
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(String value) {
            addCriterion("year =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(String value) {
            addCriterion("year <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(String value) {
            addCriterion("year >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(String value) {
            addCriterion("year >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(String value) {
            addCriterion("year <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(String value) {
            addCriterion("year <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLike(String value) {
            addCriterion("year like", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotLike(String value) {
            addCriterion("year not like", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<String> values) {
            addCriterion("year in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<String> values) {
            addCriterion("year not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(String value1, String value2) {
            addCriterion("year between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(String value1, String value2) {
            addCriterion("year not between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andMonthIsNull() {
            addCriterion("month is null");
            return (Criteria) this;
        }

        public Criteria andMonthIsNotNull() {
            addCriterion("month is not null");
            return (Criteria) this;
        }

        public Criteria andMonthEqualTo(String value) {
            addCriterion("month =", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotEqualTo(String value) {
            addCriterion("month <>", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThan(String value) {
            addCriterion("month >", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThanOrEqualTo(String value) {
            addCriterion("month >=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThan(String value) {
            addCriterion("month <", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThanOrEqualTo(String value) {
            addCriterion("month <=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLike(String value) {
            addCriterion("month like", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotLike(String value) {
            addCriterion("month not like", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthIn(List<String> values) {
            addCriterion("month in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotIn(List<String> values) {
            addCriterion("month not in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthBetween(String value1, String value2) {
            addCriterion("month between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotBetween(String value1, String value2) {
            addCriterion("month not between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andDayIsNull() {
            addCriterion("day is null");
            return (Criteria) this;
        }

        public Criteria andDayIsNotNull() {
            addCriterion("day is not null");
            return (Criteria) this;
        }

        public Criteria andDayEqualTo(String value) {
            addCriterion("day =", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotEqualTo(String value) {
            addCriterion("day <>", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayGreaterThan(String value) {
            addCriterion("day >", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayGreaterThanOrEqualTo(String value) {
            addCriterion("day >=", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayLessThan(String value) {
            addCriterion("day <", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayLessThanOrEqualTo(String value) {
            addCriterion("day <=", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayLike(String value) {
            addCriterion("day like", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotLike(String value) {
            addCriterion("day not like", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayIn(List<String> values) {
            addCriterion("day in", values, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotIn(List<String> values) {
            addCriterion("day not in", values, "day");
            return (Criteria) this;
        }

        public Criteria andDayBetween(String value1, String value2) {
            addCriterion("day between", value1, value2, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotBetween(String value1, String value2) {
            addCriterion("day not between", value1, value2, "day");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCountyIsNull() {
            addCriterion("county is null");
            return (Criteria) this;
        }

        public Criteria andCountyIsNotNull() {
            addCriterion("county is not null");
            return (Criteria) this;
        }

        public Criteria andCountyEqualTo(String value) {
            addCriterion("county =", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotEqualTo(String value) {
            addCriterion("county <>", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyGreaterThan(String value) {
            addCriterion("county >", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyGreaterThanOrEqualTo(String value) {
            addCriterion("county >=", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyLessThan(String value) {
            addCriterion("county <", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyLessThanOrEqualTo(String value) {
            addCriterion("county <=", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyLike(String value) {
            addCriterion("county like", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotLike(String value) {
            addCriterion("county not like", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyIn(List<String> values) {
            addCriterion("county in", values, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotIn(List<String> values) {
            addCriterion("county not in", values, "county");
            return (Criteria) this;
        }

        public Criteria andCountyBetween(String value1, String value2) {
            addCriterion("county between", value1, value2, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotBetween(String value1, String value2) {
            addCriterion("county not between", value1, value2, "county");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andPriceReleaseTimeIsNull() {
            addCriterion("price_release_time is null");
            return (Criteria) this;
        }

        public Criteria andPriceReleaseTimeIsNotNull() {
            addCriterion("price_release_time is not null");
            return (Criteria) this;
        }

        public Criteria andPriceReleaseTimeEqualTo(Date value) {
            addCriterion("price_release_time =", value, "priceReleaseTime");
            return (Criteria) this;
        }

        public Criteria andPriceReleaseTimeNotEqualTo(Date value) {
            addCriterion("price_release_time <>", value, "priceReleaseTime");
            return (Criteria) this;
        }

        public Criteria andPriceReleaseTimeGreaterThan(Date value) {
            addCriterion("price_release_time >", value, "priceReleaseTime");
            return (Criteria) this;
        }

        public Criteria andPriceReleaseTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("price_release_time >=", value, "priceReleaseTime");
            return (Criteria) this;
        }

        public Criteria andPriceReleaseTimeLessThan(Date value) {
            addCriterion("price_release_time <", value, "priceReleaseTime");
            return (Criteria) this;
        }

        public Criteria andPriceReleaseTimeLessThanOrEqualTo(Date value) {
            addCriterion("price_release_time <=", value, "priceReleaseTime");
            return (Criteria) this;
        }

        public Criteria andPriceReleaseTimeIn(List<Date> values) {
            addCriterion("price_release_time in", values, "priceReleaseTime");
            return (Criteria) this;
        }

        public Criteria andPriceReleaseTimeNotIn(List<Date> values) {
            addCriterion("price_release_time not in", values, "priceReleaseTime");
            return (Criteria) this;
        }

        public Criteria andPriceReleaseTimeBetween(Date value1, Date value2) {
            addCriterion("price_release_time between", value1, value2, "priceReleaseTime");
            return (Criteria) this;
        }

        public Criteria andPriceReleaseTimeNotBetween(Date value1, Date value2) {
            addCriterion("price_release_time not between", value1, value2, "priceReleaseTime");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginIsNull() {
            addCriterion("place_origin is null");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginIsNotNull() {
            addCriterion("place_origin is not null");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginEqualTo(String value) {
            addCriterion("place_origin =", value, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginNotEqualTo(String value) {
            addCriterion("place_origin <>", value, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginGreaterThan(String value) {
            addCriterion("place_origin >", value, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginGreaterThanOrEqualTo(String value) {
            addCriterion("place_origin >=", value, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginLessThan(String value) {
            addCriterion("place_origin <", value, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginLessThanOrEqualTo(String value) {
            addCriterion("place_origin <=", value, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginLike(String value) {
            addCriterion("place_origin like", value, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginNotLike(String value) {
            addCriterion("place_origin not like", value, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginIn(List<String> values) {
            addCriterion("place_origin in", values, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginNotIn(List<String> values) {
            addCriterion("place_origin not in", values, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginBetween(String value1, String value2) {
            addCriterion("place_origin between", value1, value2, "placeOrigin");
            return (Criteria) this;
        }

        public Criteria andPlaceOriginNotBetween(String value1, String value2) {
            addCriterion("place_origin not between", value1, value2, "placeOrigin");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table d_product
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 14 16:47:05 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}