package org.clesun.entity;

import java.util.Date;

public class DUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user.user_id
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user.user_name
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user.head_icon
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String headIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user.nick_name
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user.sex
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user.user_password
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user.phone_no
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user.tel
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user.email
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user.age
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user.create_time
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user.state
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_user.registertype
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    private Integer registertype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user.user_id
     *
     * @return the value of d_user.user_id
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user.user_id
     *
     * @param userId the value for d_user.user_id
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user.user_name
     *
     * @return the value of d_user.user_name
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user.user_name
     *
     * @param userName the value for d_user.user_name
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user.head_icon
     *
     * @return the value of d_user.head_icon
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getHeadIcon() {
        return headIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user.head_icon
     *
     * @param headIcon the value for d_user.head_icon
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setHeadIcon(String headIcon) {
        this.headIcon = headIcon == null ? null : headIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user.nick_name
     *
     * @return the value of d_user.nick_name
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user.nick_name
     *
     * @param nickName the value for d_user.nick_name
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user.sex
     *
     * @return the value of d_user.sex
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user.sex
     *
     * @param sex the value for d_user.sex
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user.user_password
     *
     * @return the value of d_user.user_password
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user.user_password
     *
     * @param userPassword the value for d_user.user_password
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user.phone_no
     *
     * @return the value of d_user.phone_no
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user.phone_no
     *
     * @param phoneNo the value for d_user.phone_no
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user.tel
     *
     * @return the value of d_user.tel
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user.tel
     *
     * @param tel the value for d_user.tel
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user.email
     *
     * @return the value of d_user.email
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user.email
     *
     * @param email the value for d_user.email
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user.age
     *
     * @return the value of d_user.age
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user.age
     *
     * @param age the value for d_user.age
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user.create_time
     *
     * @return the value of d_user.create_time
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user.create_time
     *
     * @param createTime the value for d_user.create_time
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user.state
     *
     * @return the value of d_user.state
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user.state
     *
     * @param state the value for d_user.state
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_user.registertype
     *
     * @return the value of d_user.registertype
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public Integer getRegistertype() {
        return registertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_user.registertype
     *
     * @param registertype the value for d_user.registertype
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    public void setRegistertype(Integer registertype) {
        this.registertype = registertype;
    }
}