package org.clesun.entity;

public class DyEquipmentChannelinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_equipment_channelinfo.channelinfo_id
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    private Long channelinfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_equipment_channelinfo.addr
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_equipment_channelinfo.electrical
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    private String electrical;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_equipment_channelinfo.illumination
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    private String illumination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_equipment_channelinfo.windSpeed
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    private String windspeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_equipment_channelinfo.windDirection
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    private String winddirection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_equipment_channelinfo.airTemperature
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    private String airtemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_equipment_channelinfo.airHumidity
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    private String airhumidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_equipment_channelinfo.rainfall
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    private String rainfall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_equipment_channelinfo.pressure
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    private String pressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_equipment_channelinfo.soilTemperature
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    private String soiltemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_equipment_channelinfo.soilHumidity
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    private String soilhumidity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_equipment_channelinfo.channelinfo_id
     *
     * @return the value of dy_equipment_channelinfo.channelinfo_id
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public Long getChannelinfoId() {
        return channelinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_equipment_channelinfo.channelinfo_id
     *
     * @param channelinfoId the value for dy_equipment_channelinfo.channelinfo_id
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public void setChannelinfoId(Long channelinfoId) {
        this.channelinfoId = channelinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_equipment_channelinfo.addr
     *
     * @return the value of dy_equipment_channelinfo.addr
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_equipment_channelinfo.addr
     *
     * @param addr the value for dy_equipment_channelinfo.addr
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_equipment_channelinfo.electrical
     *
     * @return the value of dy_equipment_channelinfo.electrical
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public String getElectrical() {
        return electrical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_equipment_channelinfo.electrical
     *
     * @param electrical the value for dy_equipment_channelinfo.electrical
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public void setElectrical(String electrical) {
        this.electrical = electrical == null ? null : electrical.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_equipment_channelinfo.illumination
     *
     * @return the value of dy_equipment_channelinfo.illumination
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public String getIllumination() {
        return illumination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_equipment_channelinfo.illumination
     *
     * @param illumination the value for dy_equipment_channelinfo.illumination
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public void setIllumination(String illumination) {
        this.illumination = illumination == null ? null : illumination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_equipment_channelinfo.windSpeed
     *
     * @return the value of dy_equipment_channelinfo.windSpeed
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public String getWindspeed() {
        return windspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_equipment_channelinfo.windSpeed
     *
     * @param windspeed the value for dy_equipment_channelinfo.windSpeed
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public void setWindspeed(String windspeed) {
        this.windspeed = windspeed == null ? null : windspeed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_equipment_channelinfo.windDirection
     *
     * @return the value of dy_equipment_channelinfo.windDirection
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public String getWinddirection() {
        return winddirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_equipment_channelinfo.windDirection
     *
     * @param winddirection the value for dy_equipment_channelinfo.windDirection
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public void setWinddirection(String winddirection) {
        this.winddirection = winddirection == null ? null : winddirection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_equipment_channelinfo.airTemperature
     *
     * @return the value of dy_equipment_channelinfo.airTemperature
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public String getAirtemperature() {
        return airtemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_equipment_channelinfo.airTemperature
     *
     * @param airtemperature the value for dy_equipment_channelinfo.airTemperature
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public void setAirtemperature(String airtemperature) {
        this.airtemperature = airtemperature == null ? null : airtemperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_equipment_channelinfo.airHumidity
     *
     * @return the value of dy_equipment_channelinfo.airHumidity
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public String getAirhumidity() {
        return airhumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_equipment_channelinfo.airHumidity
     *
     * @param airhumidity the value for dy_equipment_channelinfo.airHumidity
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public void setAirhumidity(String airhumidity) {
        this.airhumidity = airhumidity == null ? null : airhumidity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_equipment_channelinfo.rainfall
     *
     * @return the value of dy_equipment_channelinfo.rainfall
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public String getRainfall() {
        return rainfall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_equipment_channelinfo.rainfall
     *
     * @param rainfall the value for dy_equipment_channelinfo.rainfall
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public void setRainfall(String rainfall) {
        this.rainfall = rainfall == null ? null : rainfall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_equipment_channelinfo.pressure
     *
     * @return the value of dy_equipment_channelinfo.pressure
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public String getPressure() {
        return pressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_equipment_channelinfo.pressure
     *
     * @param pressure the value for dy_equipment_channelinfo.pressure
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public void setPressure(String pressure) {
        this.pressure = pressure == null ? null : pressure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_equipment_channelinfo.soilTemperature
     *
     * @return the value of dy_equipment_channelinfo.soilTemperature
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public String getSoiltemperature() {
        return soiltemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_equipment_channelinfo.soilTemperature
     *
     * @param soiltemperature the value for dy_equipment_channelinfo.soilTemperature
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public void setSoiltemperature(String soiltemperature) {
        this.soiltemperature = soiltemperature == null ? null : soiltemperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_equipment_channelinfo.soilHumidity
     *
     * @return the value of dy_equipment_channelinfo.soilHumidity
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public String getSoilhumidity() {
        return soilhumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_equipment_channelinfo.soilHumidity
     *
     * @param soilhumidity the value for dy_equipment_channelinfo.soilHumidity
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    public void setSoilhumidity(String soilhumidity) {
        this.soilhumidity = soilhumidity == null ? null : soilhumidity.trim();
    }
}