package org.clesun.entity;

public class DyFarmEquipment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_farm_equipment.farm_equipment_id
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    private Long farmEquipmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_farm_equipment.farm_id
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    private Long farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_farm_equipment.addr
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    private String addr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_farm_equipment.farm_equipment_id
     *
     * @return the value of dy_farm_equipment.farm_equipment_id
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    public Long getFarmEquipmentId() {
        return farmEquipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_farm_equipment.farm_equipment_id
     *
     * @param farmEquipmentId the value for dy_farm_equipment.farm_equipment_id
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    public void setFarmEquipmentId(Long farmEquipmentId) {
        this.farmEquipmentId = farmEquipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_farm_equipment.farm_id
     *
     * @return the value of dy_farm_equipment.farm_id
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    public Long getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_farm_equipment.farm_id
     *
     * @param farmId the value for dy_farm_equipment.farm_id
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    public void setFarmId(Long farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_farm_equipment.addr
     *
     * @return the value of dy_farm_equipment.addr
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_farm_equipment.addr
     *
     * @param addr the value for dy_farm_equipment.addr
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }
}