package org.clesun.entity;

import java.util.Date;

public class DyXzData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_xz_data.data_id
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    private Long dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_xz_data.post_code
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_xz_data.city_name
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_xz_data.lng
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    private Double lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_xz_data.lat
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_xz_data.create_time
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_xz_data.electrical
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    private String electrical;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_xz_data.illumination
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    private String illumination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_xz_data.windSpeed
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    private String windspeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_xz_data.windDirection
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    private String winddirection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_xz_data.airTemperature
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    private String airtemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_xz_data.airHumidity
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    private String airhumidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_xz_data.rainfall
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    private String rainfall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_xz_data.pressure
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    private String pressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_xz_data.soilTemperature
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    private String soiltemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_xz_data.soilHumidity
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    private String soilhumidity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_xz_data.data_id
     *
     * @return the value of dy_xz_data.data_id
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public Long getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_xz_data.data_id
     *
     * @param dataId the value for dy_xz_data.data_id
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public void setDataId(Long dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_xz_data.post_code
     *
     * @return the value of dy_xz_data.post_code
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_xz_data.post_code
     *
     * @param postCode the value for dy_xz_data.post_code
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_xz_data.city_name
     *
     * @return the value of dy_xz_data.city_name
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_xz_data.city_name
     *
     * @param cityName the value for dy_xz_data.city_name
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_xz_data.lng
     *
     * @return the value of dy_xz_data.lng
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_xz_data.lng
     *
     * @param lng the value for dy_xz_data.lng
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_xz_data.lat
     *
     * @return the value of dy_xz_data.lat
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_xz_data.lat
     *
     * @param lat the value for dy_xz_data.lat
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_xz_data.create_time
     *
     * @return the value of dy_xz_data.create_time
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_xz_data.create_time
     *
     * @param createTime the value for dy_xz_data.create_time
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_xz_data.electrical
     *
     * @return the value of dy_xz_data.electrical
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public String getElectrical() {
        return electrical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_xz_data.electrical
     *
     * @param electrical the value for dy_xz_data.electrical
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public void setElectrical(String electrical) {
        this.electrical = electrical == null ? null : electrical.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_xz_data.illumination
     *
     * @return the value of dy_xz_data.illumination
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public String getIllumination() {
        return illumination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_xz_data.illumination
     *
     * @param illumination the value for dy_xz_data.illumination
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public void setIllumination(String illumination) {
        this.illumination = illumination == null ? null : illumination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_xz_data.windSpeed
     *
     * @return the value of dy_xz_data.windSpeed
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public String getWindspeed() {
        return windspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_xz_data.windSpeed
     *
     * @param windspeed the value for dy_xz_data.windSpeed
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public void setWindspeed(String windspeed) {
        this.windspeed = windspeed == null ? null : windspeed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_xz_data.windDirection
     *
     * @return the value of dy_xz_data.windDirection
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public String getWinddirection() {
        return winddirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_xz_data.windDirection
     *
     * @param winddirection the value for dy_xz_data.windDirection
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public void setWinddirection(String winddirection) {
        this.winddirection = winddirection == null ? null : winddirection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_xz_data.airTemperature
     *
     * @return the value of dy_xz_data.airTemperature
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public String getAirtemperature() {
        return airtemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_xz_data.airTemperature
     *
     * @param airtemperature the value for dy_xz_data.airTemperature
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public void setAirtemperature(String airtemperature) {
        this.airtemperature = airtemperature == null ? null : airtemperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_xz_data.airHumidity
     *
     * @return the value of dy_xz_data.airHumidity
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public String getAirhumidity() {
        return airhumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_xz_data.airHumidity
     *
     * @param airhumidity the value for dy_xz_data.airHumidity
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public void setAirhumidity(String airhumidity) {
        this.airhumidity = airhumidity == null ? null : airhumidity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_xz_data.rainfall
     *
     * @return the value of dy_xz_data.rainfall
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public String getRainfall() {
        return rainfall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_xz_data.rainfall
     *
     * @param rainfall the value for dy_xz_data.rainfall
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public void setRainfall(String rainfall) {
        this.rainfall = rainfall == null ? null : rainfall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_xz_data.pressure
     *
     * @return the value of dy_xz_data.pressure
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public String getPressure() {
        return pressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_xz_data.pressure
     *
     * @param pressure the value for dy_xz_data.pressure
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public void setPressure(String pressure) {
        this.pressure = pressure == null ? null : pressure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_xz_data.soilTemperature
     *
     * @return the value of dy_xz_data.soilTemperature
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public String getSoiltemperature() {
        return soiltemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_xz_data.soilTemperature
     *
     * @param soiltemperature the value for dy_xz_data.soilTemperature
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public void setSoiltemperature(String soiltemperature) {
        this.soiltemperature = soiltemperature == null ? null : soiltemperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_xz_data.soilHumidity
     *
     * @return the value of dy_xz_data.soilHumidity
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public String getSoilhumidity() {
        return soilhumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_xz_data.soilHumidity
     *
     * @param soilhumidity the value for dy_xz_data.soilHumidity
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    public void setSoilhumidity(String soilhumidity) {
        this.soilhumidity = soilhumidity == null ? null : soilhumidity.trim();
    }
}