package org.clesun.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.clesun.entity.DFarm;
import org.clesun.entity.DFarmExample;

public interface DFarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_farm
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int countByExample(DFarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_farm
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int deleteByExample(DFarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_farm
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int deleteByPrimaryKey(Long farmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_farm
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int insert(DFarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_farm
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int insertSelective(DFarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_farm
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    List<DFarm> selectByExampleWithBLOBs(DFarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_farm
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    List<DFarm> selectByExample(DFarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_farm
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    DFarm selectByPrimaryKey(Long farmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_farm
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") DFarm record, @Param("example") DFarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_farm
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") DFarm record, @Param("example") DFarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_farm
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int updateByExample(@Param("record") DFarm record, @Param("example") DFarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_farm
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int updateByPrimaryKeySelective(DFarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_farm
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(DFarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_farm
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int updateByPrimaryKey(DFarm record);
}