package org.clesun.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.clesun.entity.DicDistrict;
import org.clesun.entity.DicDistrictExample;

public interface DicDistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    int countByExample(DicDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    int deleteByExample(DicDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    int deleteByPrimaryKey(Long dicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    int insert(DicDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    int insertSelective(DicDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    List<DicDistrict> selectByExampleWithBLOBs(DicDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    List<DicDistrict> selectByExample(DicDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    DicDistrict selectByPrimaryKey(Long dicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") DicDistrict record, @Param("example") DicDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") DicDistrict record, @Param("example") DicDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    int updateByExample(@Param("record") DicDistrict record, @Param("example") DicDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    int updateByPrimaryKeySelective(DicDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(DicDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_district
     *
     * @mbggenerated Fri Nov 17 16:38:55 CST 2017
     */
    int updateByPrimaryKey(DicDistrict record);
}