package org.clesun.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.clesun.entity.DProduct;
import org.clesun.entity.DProductExample;

public interface DProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int countByExample(DProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int deleteByExample(DProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int deleteByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int insert(DProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int insertSelective(DProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    List<DProduct> selectByExample(DProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    DProduct selectByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") DProduct record, @Param("example") DProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int updateByExample(@Param("record") DProduct record, @Param("example") DProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int updateByPrimaryKeySelective(DProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_product
     *
     * @mbggenerated Thu Dec 14 16:47:05 CST 2017
     */
    int updateByPrimaryKey(DProduct record);
}