package org.clesun.dao;

import org.apache.ibatis.annotations.Param;
import org.clesun.entity.DyEquipmentChannelinfo;
import org.clesun.entity.DyEquipmentChannelinfoExample;

import java.util.List;

public interface DyEquipmentChannelinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment_channelinfo
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    int countByExample(DyEquipmentChannelinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment_channelinfo
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    int deleteByExample(DyEquipmentChannelinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment_channelinfo
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    int deleteByPrimaryKey(Long channelinfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment_channelinfo
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    int insert(DyEquipmentChannelinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment_channelinfo
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    int insertSelective(DyEquipmentChannelinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment_channelinfo
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    List<DyEquipmentChannelinfo> selectByExample(DyEquipmentChannelinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment_channelinfo
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    DyEquipmentChannelinfo selectByPrimaryKey(Long channelinfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment_channelinfo
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") DyEquipmentChannelinfo record, @Param("example") DyEquipmentChannelinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment_channelinfo
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    int updateByExample(@Param("record") DyEquipmentChannelinfo record, @Param("example") DyEquipmentChannelinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment_channelinfo
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    int updateByPrimaryKeySelective(DyEquipmentChannelinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment_channelinfo
     *
     * @mbggenerated Tue Aug 15 17:20:56 CST 2017
     */
    int updateByPrimaryKey(DyEquipmentChannelinfo record);
}