package org.clesun.dao;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.clesun.entity.DyEquipment;
import org.clesun.entity.DyEquipmentExample;

import java.util.List;

public interface DyEquipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    @SelectProvider(type=DyEquipmentSqlProvider.class, method="countByExample")
    int countByExample(DyEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    @DeleteProvider(type=DyEquipmentSqlProvider.class, method="deleteByExample")
    int deleteByExample(DyEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    @Delete({
        "delete from dy_equipment",
        "where equipment_id = #{equipmentId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long equipmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    @Insert({
        "insert into dy_equipment (equipment_id, addr, ",
        "equipment_lng, equipment_lat, ",
        "farm_id)",
        "values (#{equipmentId,jdbcType=BIGINT}, #{addr,jdbcType=VARCHAR}, ",
        "#{equipmentLng,jdbcType=DOUBLE}, #{equipmentLat,jdbcType=DOUBLE}, ",
        "#{farmId,jdbcType=BIGINT})"
    })
    int insert(DyEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    @InsertProvider(type=DyEquipmentSqlProvider.class, method="insertSelective")
    int insertSelective(DyEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    @SelectProvider(type=DyEquipmentSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="equipment_id", property="equipmentId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="addr", property="addr", jdbcType=JdbcType.VARCHAR),
        @Result(column="equipment_lng", property="equipmentLng", jdbcType=JdbcType.DOUBLE),
        @Result(column="equipment_lat", property="equipmentLat", jdbcType=JdbcType.DOUBLE),
        @Result(column="farm_id", property="farmId", jdbcType=JdbcType.BIGINT)
    })
    List<DyEquipment> selectByExample(DyEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    @Select({
        "select",
        "equipment_id, addr, equipment_lng, equipment_lat, farm_id",
        "from dy_equipment",
        "where equipment_id = #{equipmentId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="equipment_id", property="equipmentId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="addr", property="addr", jdbcType=JdbcType.VARCHAR),
        @Result(column="equipment_lng", property="equipmentLng", jdbcType=JdbcType.DOUBLE),
        @Result(column="equipment_lat", property="equipmentLat", jdbcType=JdbcType.DOUBLE),
        @Result(column="farm_id", property="farmId", jdbcType=JdbcType.BIGINT)
    })
    DyEquipment selectByPrimaryKey(Long equipmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    @UpdateProvider(type=DyEquipmentSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") DyEquipment record, @Param("example") DyEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    @UpdateProvider(type=DyEquipmentSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") DyEquipment record, @Param("example") DyEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    @UpdateProvider(type=DyEquipmentSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(DyEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    @Update({
        "update dy_equipment",
        "set addr = #{addr,jdbcType=VARCHAR},",
          "equipment_lng = #{equipmentLng,jdbcType=DOUBLE},",
          "equipment_lat = #{equipmentLat,jdbcType=DOUBLE},",
          "farm_id = #{farmId,jdbcType=BIGINT}",
        "where equipment_id = #{equipmentId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(DyEquipment record);
}