package org.clesun.dao;

import org.clesun.entity.DyEquipment;
import org.clesun.entity.DyEquipmentExample;
import org.clesun.entity.DyEquipmentExample.Criteria;
import org.clesun.entity.DyEquipmentExample.Criterion;

import java.util.List;
import java.util.Map;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class DyEquipmentSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    public String countByExample(DyEquipmentExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("dy_equipment");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    public String deleteByExample(DyEquipmentExample example) {
        BEGIN();
        DELETE_FROM("dy_equipment");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    public String insertSelective(DyEquipment record) {
        BEGIN();
        INSERT_INTO("dy_equipment");
        
        if (record.getEquipmentId() != null) {
            VALUES("equipment_id", "#{equipmentId,jdbcType=BIGINT}");
        }
        
        if (record.getAddr() != null) {
            VALUES("addr", "#{addr,jdbcType=VARCHAR}");
        }
        
        if (record.getEquipmentLng() != null) {
            VALUES("equipment_lng", "#{equipmentLng,jdbcType=DOUBLE}");
        }
        
        if (record.getEquipmentLat() != null) {
            VALUES("equipment_lat", "#{equipmentLat,jdbcType=DOUBLE}");
        }
        
        if (record.getFarmId() != null) {
            VALUES("farm_id", "#{farmId,jdbcType=BIGINT}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    public String selectByExample(DyEquipmentExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("equipment_id");
        } else {
            SELECT("equipment_id");
        }
        SELECT("addr");
        SELECT("equipment_lng");
        SELECT("equipment_lat");
        SELECT("farm_id");
        FROM("dy_equipment");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        DyEquipment record = (DyEquipment) parameter.get("record");
        DyEquipmentExample example = (DyEquipmentExample) parameter.get("example");
        
        BEGIN();
        UPDATE("dy_equipment");
        
        if (record.getEquipmentId() != null) {
            SET("equipment_id = #{record.equipmentId,jdbcType=BIGINT}");
        }
        
        if (record.getAddr() != null) {
            SET("addr = #{record.addr,jdbcType=VARCHAR}");
        }
        
        if (record.getEquipmentLng() != null) {
            SET("equipment_lng = #{record.equipmentLng,jdbcType=DOUBLE}");
        }
        
        if (record.getEquipmentLat() != null) {
            SET("equipment_lat = #{record.equipmentLat,jdbcType=DOUBLE}");
        }
        
        if (record.getFarmId() != null) {
            SET("farm_id = #{record.farmId,jdbcType=BIGINT}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("dy_equipment");
        
        SET("equipment_id = #{record.equipmentId,jdbcType=BIGINT}");
        SET("addr = #{record.addr,jdbcType=VARCHAR}");
        SET("equipment_lng = #{record.equipmentLng,jdbcType=DOUBLE}");
        SET("equipment_lat = #{record.equipmentLat,jdbcType=DOUBLE}");
        SET("farm_id = #{record.farmId,jdbcType=BIGINT}");
        
        DyEquipmentExample example = (DyEquipmentExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    public String updateByPrimaryKeySelective(DyEquipment record) {
        BEGIN();
        UPDATE("dy_equipment");
        
        if (record.getAddr() != null) {
            SET("addr = #{addr,jdbcType=VARCHAR}");
        }
        
        if (record.getEquipmentLng() != null) {
            SET("equipment_lng = #{equipmentLng,jdbcType=DOUBLE}");
        }
        
        if (record.getEquipmentLat() != null) {
            SET("equipment_lat = #{equipmentLat,jdbcType=DOUBLE}");
        }
        
        if (record.getFarmId() != null) {
            SET("farm_id = #{farmId,jdbcType=BIGINT}");
        }
        
        WHERE("equipment_id = #{equipmentId,jdbcType=BIGINT}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_equipment
     *
     * @mbggenerated Tue Nov 14 11:47:37 CST 2017
     */
    protected void applyWhere(DyEquipmentExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}