package org.clesun.dao;

import org.apache.ibatis.annotations.Param;
import org.clesun.entity.DyFarmEquipment;
import org.clesun.entity.DyFarmEquipmentExample;

import java.util.List;

public interface DyFarmEquipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_farm_equipment
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    int countByExample(DyFarmEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_farm_equipment
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    int deleteByExample(DyFarmEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_farm_equipment
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    int deleteByPrimaryKey(Long farmEquipmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_farm_equipment
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    int insert(DyFarmEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_farm_equipment
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    int insertSelective(DyFarmEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_farm_equipment
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    List<DyFarmEquipment> selectByExample(DyFarmEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_farm_equipment
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    DyFarmEquipment selectByPrimaryKey(Long farmEquipmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_farm_equipment
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    int updateByExampleSelective(@Param("record") DyFarmEquipment record, @Param("example") DyFarmEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_farm_equipment
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    int updateByExample(@Param("record") DyFarmEquipment record, @Param("example") DyFarmEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_farm_equipment
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    int updateByPrimaryKeySelective(DyFarmEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_farm_equipment
     *
     * @mbggenerated Thu Aug 17 15:52:03 CST 2017
     */
    int updateByPrimaryKey(DyFarmEquipment record);

    int farmEquipmentAdd(@Param("list") List<DyFarmEquipment> list);
}