package org.clesun.dao;

import org.apache.ibatis.annotations.Param;
import org.clesun.entity.DyXzData;
import org.clesun.entity.DyXzDataExample;

import java.util.List;

public interface DyXzDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_xz_data
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    int countByExample(DyXzDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_xz_data
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    int deleteByExample(DyXzDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_xz_data
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    int deleteByPrimaryKey(Long dataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_xz_data
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    int insert(DyXzData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_xz_data
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    int insertSelective(DyXzData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_xz_data
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    List<DyXzData> selectByExample(DyXzDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_xz_data
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    DyXzData selectByPrimaryKey(Long dataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_xz_data
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") DyXzData record, @Param("example") DyXzDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_xz_data
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    int updateByExample(@Param("record") DyXzData record, @Param("example") DyXzDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_xz_data
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    int updateByPrimaryKeySelective(DyXzData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dy_xz_data
     *
     * @mbggenerated Thu Aug 17 18:49:39 CST 2017
     */
    int updateByPrimaryKey(DyXzData record);
}